# This action automatically labels Pull-Requests
# based on files edited and no of lines changed.
name: Size Labeler/Checker
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested
      - edited
jobs:
  label-changes:
    if: vars.SMALL_THRESHOLD && vars.MODERATE_THRESHOLD && vars.LARGE_THRESHOLD && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout pull request repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Checkout the set_label_by_changes.sh file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .ci
            .github
          repository: amanmoon/sage
          path: sage
      - name: Add labels based on size
        run: |
          git fetch origin $BASE_REF
          chmod a+x sage/.ci/set_labels_by_changes.sh
          sage/.ci/set_labels_by_changes.sh
        env:
          BASE_REF: ${{ github.base_ref }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number}}
          SMALL_THRESHOLD: ${{ vars.SMALL_THRESHOLD }}
          MODERATE_THRESHOLD: ${{ vars.MODERATE_THRESHOLD }}
          LARGE_THRESHOLD: ${{ vars.LARGE_THRESHOLD }}
